<Project Sdk="Aspire.AppHost.Sdk/13.4.0">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Casko.Messaging.Email.Api/Casko.Messaging.Email.Api.csproj" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" Version="13.4.0" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
  </ItemGroup>
</Project>
